export const AppConstants = {
    //Login and Register
    LOGIN: 'Login',
    EMAIL: 'Email',
    PASSWORD: 'Password',
    FULL_NAME: 'Full Name',
    CONFIRM_PASSWORD: 'Confirm Password',
    REGISTER: 'Register',
    FORGOT_PASSWORD: 'Forgot Password?',
    LOGIN_HERE: 'Login here!',
    DO_NOT_HAVE_AN_ACCOUNT: 'Don\'t have an account?',
    ALREADY_HAVE_AN_ACCOUNT: 'Already have an account?',
    SIGN_UP: 'Sign Up',
    LOGGED_IN_SUCCESSFULLY: 'Logged in successfully!',
    EMAIL_IS_REQUIRED: 'Email is required',
    INVALID_EMAIL_ADDRESS: 'Invalid email address',
    PASSWORD_IS_REQUIRED: 'Password is required',
    FULL_NAME_IS_REQUIRED: 'Full Name is required',
    CONFIRM_PASSWORD_IS_REQUIRED: 'Confirm Password is required',
    PASSWORDS_DO_NOT_MATCH: 'Passwords do not match',
    REGISTERED_SUCCESSFULLY_PLEASE_LOGIN: 'Registered successfully, please login!',
    PLEASE_ACCEPT: 'Please accept',
    TERMS_AND_CONDITIONS: 'Terms & Conditions!',
    YOU_MUST_ACCEPT_THE_TERMS_AND_CONDITIONS: 'You must accept the terms and conditions',
    //Home
    USER_LOGGED_OUT_SUCCESSFULLY: 'User logged out successfully!',
    APP_NAME: 'Punjabi Suit House',
    HOME: 'Home',
    MANAGE_STOCK: 'Manage Stock',
    SUIT_DETAIL_ADDED_SUCCESSFULLY: 'Suit detail added successfully',
    ADD_SUIT_INFORMATION: 'Add Suit Information',
    SUIT_TYPE: 'Suit Type',
    SUIT_PRICE: 'Suit Price',
    ETHNIC: 'Ethnic',
    PATIALA_SUIT: 'Patiala Suit',
    AFGHANI_STYLE_SUIT: 'Afghani Style Suit',
    PUBLISH: 'Publish',
    SUIT_DESCRIPTION: 'Suit Description',
    SUIT_TYPE_IS_REQUIRED: 'Suit type is required',
    SUIT_PRICE_IS_REQUIRED: 'Suit Price is required',
    SUIT_DESCRIPTION_IS_REQUIRED: 'Suit Description is required',
    SUIT_INFORMATION_UPDATED_SUCCESSFULLY: 'Suit information updated successfully!',
    SUIT_INFORMATION_DELETED_SUCCESSFULLY: 'Suit information deleted successfully!',
    ACTION: 'Action',
    S_NO: 'S No.',
    MANAGE_SUITS_STOCKS: 'Manage Suits Stocks',
    EDIT: 'Edit',
    EDIT_SUIT_INFORMATION: 'Edit Suit Information',
    UPDATE: 'Update',
    CANCEL: 'Cancel',
    REMOVE: 'Remove',
}